project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5450- Jiahui Liu"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: intro.qmd
        text: Introduction
      - href: Literature.qmd
        text: Literature Review
      - href: Data.qmd
        text: Data&Methods
      - href: Results.qmd
        text: Results
      - href: Policy.qmd
        text: "Policy Recommendation"

  
format:
  html:
    theme: minty
    toc: true



